Add support for Node 16 (LTS)
vercel/og-image pull request #199
Opened 2022-03-11 12:13 UTC by marcofranssen

2022-03-11 20:34 UTC, styfle requested changes
This needs to be deployed with 14.x at this time since `chrome-aws-lambda` doesn't support 16.x

Here's the upstream PR https://github.com/alixaxel/chrome-aws-lambda/pull/274

2022-03-14 14:32 UTC, styfle commented
If its working fine locally, why does the config need to change?

2022-03-16 20:46 UTC, marcofranssen commented
> If its working fine locally, why does the config need to change?

Otherwise it just errors with a message Node 14 is required.

2022-03-17 16:29 UTC, styfle commented
What is the error? Can you use `--ignore-engines` flag?

2022-03-30 15:20 UTC, marcofranssen commented
> What is the error? Can you use `--ignore-engines` flag?

See below the error and tryout of `--ignore-engines`.

```shell
$ yarn build --ignore-engines
yarn run v1.22.18
error @: The engine "node" is incompatible with this module. Expected version "14.x". Got "16.14.2"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2022-03-30 22:58 UTC, styfle commented
It works with `yarn --ignore-engines build`

2022-03-31 09:42 UTC, marcofranssen commented
Is it OK to add that as a fix in this PR? Otherwise I'm still stuck with the fact I can't use it out of the box.

I either have to change the supported node version or I have to change this build script.

2022-10-11 08:45 UTC, marcofranssen commented
To make it work locally. Otherwise you get the error only node 14 is supported

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Steven ***@***.***>
Sent: Monday, March 14, 2022 3:32:47 PM
To: vercel/og-image ***@***.***>
Cc: Marco Franssen ***@***.***>; Author ***@***.***>
Subject: Re: [vercel/og-image] Add support for Node 16 (LTS) (PR #199)


If its working fine locally, why does the config need to change?

—
Reply to this email directly, view it on GitHub<https://github.com/vercel/og-image/pull/199#issuecomment-1066873313>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAFJTTKMA2VZ4EGQ2ERSPDDU75EY7ANCNFSM5QPOU3GQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-20 23:28 UTC, styfle commented
Closing in favor of #226

2023-01-20 23:28 UTC, closed without merging